'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblActivite
    Public Property noActivite As Byte
    Public Property nomActivite As String
    Public Property descActivite As String

    Public Overridable Property tblForfait As ICollection(Of tblForfait) = New HashSet(Of tblForfait)

End Class
