'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblChambre
    Public Property noChambre As Short
    Public Property noHotel As Byte
    Public Property statutChambre As String
    Public Property codeTypeChambre As String

    Public Overridable Property tblHotel As tblHotel
    Public Overridable Property tblTypeChambre As tblTypeChambre

End Class
