'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblForfait
    Public Property noForfait As Byte
    Public Property descForfait As String
    Public Property etatForfait As String
    Public Property prixForfait As Decimal
    Public Property noHotel As Byte

    Public Overridable Property tblHotel As tblHotel
    Public Overridable Property tblActivite As ICollection(Of tblActivite) = New HashSet(Of tblActivite)
    Public Overridable Property tblOption As ICollection(Of tblOption) = New HashSet(Of tblOption)

End Class
