'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTypeChambre
    Public Property codeTypeChambre As String
    Public Property nomTypeChambre As String
    Public Property prixChambre As Decimal

    Public Overridable Property tblGabarit As ICollection(Of tblGabarit) = New HashSet(Of tblGabarit)
    Public Overridable Property tblChambre As ICollection(Of tblChambre) = New HashSet(Of tblChambre)
    Public Overridable Property tblRabais As ICollection(Of tblRabais) = New HashSet(Of tblRabais)
    Public Overridable Property tblHotel As ICollection(Of tblHotel) = New HashSet(Of tblHotel)
    Public Overridable Property tblOption As ICollection(Of tblOption) = New HashSet(Of tblOption)

End Class
